import { readFileSync } from 'fs'
import { join } from 'path'

/**
 * Animated background sketch — a contour trace of the canonical crash-test
 * dummy reference image (head + face + reticle eye + ribbed neck).
 *
 * Generated by /tmp/trace-dummy.py using OpenCV: thresholds for dark pixels
 * (the cartoon outlines) → finds contours → simplifies polygons → emits
 * SVG paths with pathLength="1" and a CSS variable --i per path.
 *
 * 19 paths total. Each animates via stroke-dasharray draw-on, with the
 * stagger delay sourced from the --i variable so big shapes (head, neck)
 * draw first and details (eyes, reticle) fill in after.
 */
export function DummySketch() {
  const svgPath = join(process.cwd(), 'public/brand/dummy-traced.svg')
  const svg = readFileSync(svgPath, 'utf-8')

  return (
    <div
      className="dummy-sketch"
      aria-hidden="true"
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  )
}
